apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnect
metadata:
  name: connect-cluster
spec:
  replicas: 1
  bootstrapServers: production-ready-kafka-bootstrap.amq-streams.svc:9092
  authentication:
    type: scram-sha-512
    username: secure-topic-reader
    passwordSecret:
      secretName: secure-topic-reader
      password: password
